<?php
date_default_timezone_set("Asia/kolkata");
session_start();
$email=$_SESSION['email'];
require('../fpdf/fpdf.php');
$conn = new mysqli('localhost', 'root', '', 'expense');
$select="SELECT * from register INNER JOIN expenses ON register.id=expenses.id where email='$email'";
$result = $conn->query($select);
$pdf = new FPDF();
$pdf->SetLeftMargin(25);
$pdf->AddPage();
$pdf->SetFont('Times','B',14);
while($row = $result->fetch_object()){
  $id = $row->id;
  $name = $row->name;
  $email = $row->email;
  $rent=$row->rent;
  $groceries=$row->groceries;
  $education=$row->education;
  $electricity=$row->electricity;
  $clothes=$row->clothes;
  $personal=$row->personal;
  $gas=$row->gas;
  $medical=$row->medical;
  $insurance=$row->insurance;
  $transport=$row->transport;
  $income=$row->income;
  $total=$rent+$groceries+$education+$electricity+$clothes+$clothes+$gas+$medical+$insurance+$transport;
  $pdf->SetTextColor(255,0,0);
  $pdf->Cell(160,10,"EXPENSE DATA",0,1,"C");
  $pdf->Ln();
  $pdf->SetTextColor(0,0,0);
  $pdf->Cell(20,10,'Name:');
  $pdf->Cell(100,10,$name);
  $pdf->Cell(13,10,'Date:');
  $pdf->Cell(40,10,Date('d/m/Y'));
  $pdf->Ln();
  $pdf->Cell(20,10,'Email:');
  $pdf->Cell(100,10,$email);
  $pdf->Cell(13,10,'Time:');
  $pdf->Cell(40,10,Date('h:i:s A'));
  $pdf->Ln();
  $pdf->Ln();
  $pdf->SetFillColor(90,90,90);
  $pdf->SetTextColor(255,255,255);
  $pdf->Cell(80,10,'Purpose',1,0,"C",True);
  $pdf->Cell(80,10,'Amount',1,0,"C",True);
  $pdf->Ln();
  $pdf->SetTextColor(100,100,100);
  $pdf->Cell(80,10,'Rent',1,0,"C");
  $pdf->Cell(80,10,$rent,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Groceries',1,0,"C");
  $pdf->Cell(80,10,$groceries,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Education',1,0,"C");
  $pdf->Cell(80,10,$education,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Electricity',1,0,"C");
  $pdf->Cell(80,10,$electricity,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Clothes',1,0,"C");
  $pdf->Cell(80,10,$clothes,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Personal',1,0,"C");
  $pdf->Cell(80,10,$personal,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Gas',1,0,"C");
  $pdf->Cell(80,10,$gas,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Medical',1,0,"C");
  $pdf->Cell(80,10,$medical,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Insurance',1,0,"C");
  $pdf->Cell(80,10,$insurance,1,0,"C");
  $pdf->Ln();
  $pdf->Cell(80,10,'Transport',1,0,"C");
  $pdf->Cell(80,10,$transport,1,0,"C");
  $pdf->Ln();
  $pdf->SetFillColor(230,230,230);
  $pdf->Cell(80,10,'Total',1,0,"C",True);
  $pdf->Cell(80,10,$total,1,0,"C",True);
  $pdf->Ln();
  $pdf->Ln();
  if($income-$total>0){
    $pdf->Cell(80,10,'Saving of this Month is :');
    $pdf->Cell(80,10,$income-$total);
  }else{
    $pdf->Cell(80,10,'Extra Expense of this month is :');
    $pdf->Cell(80,10,$total-$income);
  }
}
$pdf->Output();
?>